### ISSUE TITLE
GitVersion configuration

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#321]
GitVersion version 3.6.3 requires `GitVersion.yml` (`yml`, not `yaml`) with the following content:

```
assembly-versioning-scheme: Major
next-version: 6.0
branches:
  develop:
    tag: alpha
  releases?[/-]:
    tag: rc
```

Core has already applied that to [RC1](https://github.com/Particular/NServiceBus/blob/release-6.0.0/GitVersion.yml).  Should NSB.ASB do the same? /cc @danielmarbach
